mytestsite/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from mytestsite import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('test_django.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

test_django/urls.py
from django.conf.urls.static import static
from django.urls import path
from .views import *

urlpatterns = [
    path('', homePage, name='gallery'),
    path('album-page/<int:album_id>/', albumPage, name='albumPage'),
    path('addphoto/', addPhotoPage, name='addphoto'),
    path('picture-open/<int:pic_id>/', PhotoForm.as_view(), name='pictureOpen'),
    path('profile/<int:pk>/', ProfileView.as_view(), name='profile'),
    path('profile/edit/<int:pk>/', ProfileEditView.as_view(), name='profile-edit'),
    path('picture-open/<int:pic_id>/comment/<int:pk>/reply', CommentReplyView.as_view(), name='comment-reply'),
    path('picture-open/<int:pic_id>/comment/delete/<int:pk>/', CommentDeleteView.as_view(), name='comment-delete'),
    path('add-album/', addAlbumPage, name='add_album'),
    path('picture-open/<int:pk>/dislike', AddDislike.as_view(), name='dislike'),
    path('update_photo/<str:pk>/update', updatePhoto, name="update_photo"),
    path('delete_photo/<str:pk>/', deletePhoto, name="delete_photo"),
    path('edit_album/<int:pk>/', edit_album, name="edit_album"),
    path('profile/<int:pk>/followers/', ListFollowers.as_view(), name='list-followers'),
    path('profile/<int:pk>/followers/add', AddFollower.as_view(), name='add-follower'),
    path('profile/<int:pk>/followers/remove', RemoveFollower.as_view(), name='remove-follower'),
    path('picture-open/<int:photo_pk>/comment/<int:pk>/like', AddCommentLike.as_view(), name='comment_likes'),
    path('picture-open/<int:photo_pk>/comment/<int:pk>/dislike', AddCommentDislike.as_view(), name='comment_dislikes'),
    path('search/', UserSearch.as_view(), name='profile-search'),
    path('notification/<int:notification_pk>/post/<int:post_pk>', PostNotification.as_view(), name='post-notification'),
    path('notification/<int:notification_pk>/profile/<int:profile_pk>', FollowNotification.as_view(),
         name='follow-notification'),
    path('notification/delete/<int:notification_pk>', RemoveNotification.as_view(), name='notification-delete'),
    path('chat/', FindChatRoom.as_view(), name='index'),
    path('chat/<str:room_name>/', ChatDialogue.as_view(), name='room'),
    path('like/', like, name='like'),

]

test_django/models.py
import datetime

from django.contrib.auth.decorators import login_required
from django.core import signals
from django.db import models
from django.conf import settings
from django.contrib.auth import get_user_model
from django.core.signals import request_finished
from django.http import JsonResponse
from django.shortcuts import get_object_or_404
from django.utils import timezone
from django.dispatch.dispatcher import receiver
from django.db.models.signals import *
import uuid

# from imagekit.models import ImageSpecField
# from imagekit.processors import ResizeToFill

User = get_user_model()


class Album(models.Model):
    name = models.TextField(max_length=1000)
    cover = models.ImageField(upload_to=settings.MEDIA_ROOT)
    description = models.TextField()
    # cover1 = ImageSpecField([
    #         ResizeToFill(200, 200)], source='cover',
    #         format='JPEG', options={'quality': 90})


@receiver(pre_delete, sender=Album)
def mymodel_delete(sender, instance, **kwargs):
    instance.cover.delete(False)


class Photo(models.Model):
    image = models.ImageField(upload_to=settings.MEDIA_ROOT)
    album = models.ForeignKey('Album', on_delete=models.CASCADE)
    description = models.TextField()
    created_on = models.DateTimeField(auto_created=timezone.now(), blank=True, null=True)
    author = models.ForeignKey(User, null=True, on_delete=models.CASCADE, db_constraint=False)
    likes = models.ManyToManyField(User, related_name='like', default=None, blank=True)
    like_count = models.BigIntegerField(default='0')
    favourites = models.ManyToManyField(
        User, related_name='favourite', default=None, blank=True)
    dislikes = models.ManyToManyField(User, blank=True, related_name='dislikes')
    photo_views = models.IntegerField(default=0, null=True, blank=True)
    tags = models.ManyToManyField('Tag', blank=True)

    # def __str__(self):
    #     return self.description

    # def total_likes(self):
    #     return self.likes.count()

    def create_tags(self):
        for word in self.description.split():
            if (word[0] == '#'):
                tag = Tag.objects.filter(name=word[1:]).first()
                if tag:
                    self.tags.add(tag.pk)
                else:
                    tag = Tag(name=word[1:])
                    tag.save()
                    self.tags.add(tag.pk)
                self.save()

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.created_on <= now

    class Meta:
        ordering = ['-created_on']


class Comments(models.Model):
    comment = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    photo = models.ForeignKey('Photo', related_name='comments', on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    likes = models.ManyToManyField(User, blank=True, related_name='comment_likes')
    dislikes = models.ManyToManyField(User, blank=True, related_name='comment_dislikes')
    parent = models.ForeignKey('self', on_delete=models.CASCADE, blank=True, null=True, related_name='+')
    tags = models.ManyToManyField('Tag', blank=True)

    def create_tags(self):
        for word in self.comment.split():
            if (word[0] == '#'):
                tag = Tag.objects.get(name=word[1:])
                if tag:
                    self.tags.add(tag.pk)
                else:
                    tag = Tag(name=word[1:])
                    tag.save()
                    self.tags.add(tag.pk)
                self.save()

    def __str__(self):
        return '%s-%s' % (self.photo.description, self.author)

    @property
    def children(self):
        return Comments.objects.filter(parent=self).order_by('-created_on').all()

    @property
    def is_parent(self):
        if self.parent is None:
            return True
        return False


class UserProfile(models.Model):
    user = models.OneToOneField(User, primary_key=True, verbose_name='user', related_name='profile',
                                on_delete=models.CASCADE)
    name = models.CharField(max_length=30, blank=True, null=True)
    bio = models.TextField(max_length=500, blank=True, null=True)
    birth_date = models.DateField(null=True, blank=True)
    location = models.CharField(max_length=100, blank=True, null=True)
    picture = models.ImageField(upload_to='uploads/profile_pictures', default='uploads/profile_pictures/default.png',
                                blank=True)
    followers = models.ManyToManyField(User, blank=True, related_name='followers')


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        UserProfile.objects.create(user=instance)


@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()


class Notification(models.Model):
    # 1 = Like, 2 = Comment, 3 = Follow
    notification_type = models.IntegerField()
    to_user = models.ForeignKey(User, related_name='notification_to', on_delete=models.CASCADE, null=True)
    from_user = models.ForeignKey(User, related_name='notification_from', on_delete=models.CASCADE, null=True)
    photo = models.ForeignKey('Photo', on_delete=models.CASCADE, related_name='+', blank=True, null=True)
    comment = models.ForeignKey('Comments', on_delete=models.CASCADE, related_name='+', blank=True, null=True)
    date = models.DateTimeField(default=timezone.now)
    user_has_seen = models.BooleanField(default=False)


class Tag(models.Model):
    name = models.CharField(max_length=255)


class Chat(models.Model):
    content = models.CharField(max_length=1000)
    timestamp = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    room = models.ForeignKey('ChatRoom', on_delete=models.CASCADE)


class ChatRoom(models.Model):
    name = models.CharField(max_length=255)

test_django/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.forms import ModelForm
from .models import *


class ImageForm(forms.ModelForm):
    class Meta:
        model = Photo
        fields = ('album', 'description')


class AlbumForm(forms.ModelForm):
    class Meta:
        model = Album
        fields = ('name', 'cover', 'description')


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'password1', 'password2']

    def __init__(self, *args, **kwargs):
        super(CustomUserCreationForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget.attrs.update(
            {'class': 'form-control', 'placeholder': 'Enter username...'})
        self.fields['password1'].widget.attrs.update(
            {'class': 'form-control', 'placeholder': 'Enter password...'})
        self.fields['password2'].widget.attrs.update(
            {'class': 'form-control', 'placeholder': 'Confirm password...'})


class CommentForm(ModelForm):
    class Meta:
        model = Comments
        fields = ['comment']

    comment = forms.CharField(
        label='',
        widget=forms.Textarea(
            attrs={'rows': '3',
                   'placeholder': 'Say Something...'}
        ))

test_django/templates/add_album.html
<link rel="stylesheet" href="/static/css/style.css?v=2.9"/>
{% extends "base.html" %}
{% block title %} Gallery-add/album {% endblock %}

{% block content %}
<a href="{% url 'gallery'%}" class="btn btn-dark my-3">Go Back</a>
<br>
<div class="align_div">
    <form enctype="multipart/form-data" method="post" id="album_form">


        <div>
            <h6> Name: </h6>
            <textarea name="name" cols="40" rows="1" class="vLargeTextField" maxlength="1000" id="id_name"></textarea>
        </div>
        <br>
        <div>
            <h6> Cover:</h6>
            <input type="file" name="cover" accept="image/*" id="id_cover">
        </div>
        <br>
        <div>
            <h6> Description: </h6><br>
            <textarea name="description" cols="40" rows="8" class="vLargeTextField" required="" id="id_description"
                      placeholder="Description..."></textarea>
        </div>
        <br>
        <div>
            <input class="btn btn-outline-success" type="submit" value="Save" name="_save">
        </div>


    </form>
</div>
{% endblock %}

test_django/templates/add_photo.html
<link rel="stylesheet" href="/static/css/style.css?v=2.9"/>
{% extends "base.html" %}
{% block title %} Gallery-add/pic {% endblock %}


<h1>Add photo to album</h1>

{% block content %}
<a href="{% url 'albumPage' album.id%}" class="btn btn-dark my-3">Go Back</a>
<br><br>

<form enctype="multipart/form-data" method="post" id="photo_form" novalidate="">


    <input type="hidden" class="vDateField" size="10" value="{{album.id}}">
    <input type="hidden" name="author" required="" id="id_author" value="{{request.user}}">
    <div class="align_div">

        <div>
            <h6>Image:</h6>
            <input type="file" name="photo" accept="image/*" required="" id="photo">
        </div>
        <br>
        <div>
            <h6>Description:</h6>
            <textarea name="description" cols="40" rows="10" class="vLargeTextField" required="" id="id_description "
                      placeholder="Description..."></textarea>
        </div>

        <input type="hidden" name="album" value="{{album.id}}">


        <br>
        <div class="submit-row">
            <input class="btn btn-outline-success" type="submit" value="Save"  name="_save">
        </div>
    </div>
</form>

{% endblock %}

test_django/templates/album_page.html
{% extends "base.html" %}


{% block content %}
<a href="{% url 'gallery'%}" class="btn btn-dark my-3">Go Back</a>

{% if request.user == "vlad" %}
<a href="{% url 'edit_album' album.id %}?album_id={{album.id}}" class="btn btn-dark my-3">-Edit album properties-</a>
{% endif %}
{% if album.name%}
<h3 align="center"> Album name: {{album.name}}</h3>
{% endif %}
<div class="container">

    <a href="{% url 'addphoto' %}?album_id={{album.id}}" class="btn btn-dark my-3">-Add Photo-</a>
    <!--<a href="{% url 'account_logout' %}" class="btn btn-dark btn-block btn-sm m-1">Logout</a>-->


</div>
<!--<form  method="POST" >-->
<!--<button type="submit" class="btn btn-outline-secondary"><input type="hidden" name="order_date" value="{{1}}">order_by date</button>-->
<!--    &lt;!&ndash;<a href="{% url 'addphoto' %}}">Add photo</a>&ndash;&gt;-->
<!--</form>-->


<!--<form  method="POST" >-->
<!--<button type="submit" class="btn btn-outline-secondary"><input type="hidden" name="order_views" value="{{2}}">order by views</button>-->
<!--</form>-->

<div class="row">
    {% for photo in photos %}
    <div class="col-xs-6 col-sm-3" style="display: inline-block;">
        <a href="{% url 'pictureOpen' photo.id %}?album_id={{album.id}}"> <img src="{{ photo.image.url }}"
                                                                               class="w-100 shadow-1-strong rounded mb-4"></a>
    </div>
    {% endfor %}
</div>
{% endblock %}

test_django/templates/base.html
<!doctype html>
{% load static %}
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <link rel="stylesheet" href="{% static 'css/style.css'%}">
    {% block head %}{% endblock %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <title>{% block title %} {% endblock %}</title>
</head>

<body>
<!-- Navigation -->

{% load account %}
{% load custom_tags %}
<!--<style>#third{background: url("/static/bg_pic.jpeg") 50% 0 no-repeat fixed;}</style>-->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
        <a class="navbar-brand" href="{% url 'gallery' %}">Django 3 | Gallery-Project</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">

                {% if request.user.is_authenticated %}

                <li style="padding-right: 50px;">
                    <form class="d-flex" method="GET" action="{% url 'profile-search' %}">
                        <div class="input-group">
                            <span class="input-group-text" id="basic-addon1">@</span>
                            <input class="form-control mr-sm-2" type="search" placeholder="Search user"
                                   aria-label="Search user" name="query" value="{{ request.GET.query }}">
                            <button class="btn btn-outline-info my-2 my-sm-0" type="submit">Search</button>
                        </div>
                    </form>
                </li>

                <li class="nav-item">
                    <a href="{% url 'profile' request.user.profile.pk %}" style="color: white;font-weight: bold;margin-right:10px;">Profile:
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                             class="bi bi-person" viewBox="0 0 16 16">
                            <path d="M8 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6zm2-3a2 2 0 1 1-4 0 2 2 0 0 1 4 0zm4 8c0 1-1 1-1 1H3s-1 0-1-1 1-4 6-4 6 3 6 4zm-1-.004c-.001-.246-.154-.986-.832-1.664C11.516 10.68 10.289 10 8 10c-2.29 0-3.516.68-4.168 1.332-.678.678-.83 1.418-.832 1.664h10z"/>
                        </svg>
                    </a></li>
                <li class="nav-item" style="color: white;font-weight: bold;margin-right:10px;">
                    {% show_notifications %}
                </li>
                <li class="nav-item">

                    <h7 style="font-family:courier; color:white;font-weight: bold;"> Current user: {{user.username}} |</h7>
                    <a href="{% url 'account_logout' %}">
                        <h7 style="font-family:courier; color:white;">Выйти</h7>
                    </a>
                    {% else %}
                    <a href="{% url 'account_signup' %}">
                        <h7 style="font-family:courier; color:white;">Регистрация |</h7>
                    </a> <a href="{% url 'account_login' %}">
                    <h7 style="font-family:courier; color:white;">Войти</h7>
                </a>

                    {% endif %}
                </li>
            </ul>
        </div>
    </div>
</nav>
<br><br><br><br>
<div class="container">
    {% block content %} {% endblock %}

</div>

<!--    &lt;!&ndash; Optional JavaScript &ndash;&gt;-->
<!--    &lt;!&ndash; jQuery first, then Popper.js, then Bootstrap JS &ndash;&gt;-->
<!--    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>-->
<!--    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>-->
<!--    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>-->

</body>
</html>

test_django/templates/comment_delete.html
{% extends "base.html" %}
{% block title %} Gallery {% endblock %}
{% block content %}
<div class="container">
    <div class="row mt-5">
        <div class="col-md-5 col-sm-6">
            <a href="{% url 'pictureOpen' object.photo.pk %}" class="btn btn-light">Back To Post</a>
        </div>
    </div>

    <div class="row justify-content-center mt-3 mb-5">
        <div class="col-md-5 col-sm-12 border-bottom">
            <form method="POST">
                {% csrf_token %}
                <h5>Are You Sure?</h5>
                <p>You are about to delete this comment, this cannot be undone.</p>
                <div class="d-grid gap-2">
                    <button class="btn btn-danger mt-3">Delete</button>
                </div>
            </form>
        </div>
    </div>
</div>


{% endblock %}

test_django/templates/delete_photo.html
{% extends "base.html" %}

{% block title %} Gallery-del/pic {% endblock %}
{% block content %}

<br>
<div class="row">
    <div class="col-md-6">
        <div class="card card-body">


            <p>Are you sure you want to delete "{{photo}}"?</p>

            <form action="{% url 'delete_photo' photo.id  %}" method="POST">

                {% csrf_token %}
                <a class="btn btn-warning" href="{% url 'gallery' %}">Cancel</a>

                <input class="btn btn-danger" type="submit" name="Confirm">
            </form>
        </div>
    </div>
</div>

{% endblock %}

test_django/templates/edit_album.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %} Gallery-update/pic {% endblock %}
{% block content %}
<form action="" method="POST">
    {% csrf_token %}
    {{form|crispy}}
    <input type="submit" name="Submit">
</form>


{% endblock %}

test_django/templates/photo.html
<!DOCTYPE html>
<html>
{% load crispy_forms_tags %}
{% load hitcount_tags %}
<head>
    <meta charset='utf-8'>
    <meta http-equiv='X-UA-Compatible' content='IE=edge'>
    <title>Photo</title>
    <meta name='viewport' content='width=device-width, initial-scale=1'>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">

</head>

<body class="m-5">
<p>Views: {% get_hit_count for photo %}</p>
<div class="container">

    <a href="{% url 'gallery' %}" class="btn btn-dark my-3">Go Back</a>
    <div style="height: 90vh;">
        <img style="max-width: 100%; max-height: 100%;" src="{{photo.image.url}}">
        <!--                    # Return total hits for an object:-->
        <p>{{photo.description}}</p>
    </div>
</div>

<div class="row justify-content-center mt-3">
    <div class="col-md-5 col-sm-12">
        <h5>Add a Comment!</h5>
    </div>
</div>
<div class="row justify-content-center mt-3 mb-5">
    <div class="col-md-5 col-sm-12">
        <form method="POST">
            {% csrf_token %}
            {{ form | crispy }}
            <div class="d-grid gap-2">
                <button class="btn btn-success mt-3">Submit!</button>
            </div>
        </form>
    </div>
</div>
{% for comment in comments %}
<div class="row justify-content-center mt-3 mb-5 border-bottom">
    <div class="col-md-5 col-sm-12">
        <p>
            <strong>{{ comment.author }}</strong> {{ comment.created_on }}
        </p>
        <p>{{ comment.comment }}</p>
    </div>
</div>
{% endfor %}
</div>

</body>

</html>

test_django/templates/profile_edit.html
{% extends "base.html" %}
{% block title %} Gallery {% endblock %}
{% load crispy_forms_tags %}
{% block content %}
<div class="container">
    <div class="row mt-5">
        <div class="col-md-5 col-sm-6">
            <a href="{% url 'profile' object.pk %}" class="btn btn-light">Back To Profile</a>
        </div>
    </div>

    <div class="row justify-content-center mt-3">
        <div class="col-md-5 col-sm-12 border-bottom">
            <h5>Update Your Profile</h5>
        </div>
    </div>

    <div class="row justify-content-center mt-3 mb-5">
        <div class="col-md-5 col-sm-12 border-bottom">
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form | crispy }}
                <br>
                <div class="d-grid gap-2">
                    <button class="btn btn-outline-success">Submit</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

test_django/templates/register.html
{% extends 'base.html' %}

{% block title %}Регистрация{% endblock %}

{% block content %}
<h2>Log In</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Log In</button>
</form>
{% endblock %}

test_django/templates/search_user.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <div class="row mt-5">
        <div class="col-md-5 col-sm-6">
            <a href="{% url 'gallery' %}" class="btn btn-outline-info my-2 my-sm-0">Back To Feed</a>
        </div>
    </div>

    {% for profile in profile_list %}
    <div class="row justify-content-center mt-3">
        <div class="col-md-5 col-sm-12 border-bottom position-relative">
            <p><a style="text-decoration: none;" class="text-primary" href="{% url 'profile' profile.pk %}">@{{
                profile.user }}</a></p>
            {% if profile.location %}
            <p>{{ profile.location }}</p>
            {% endif %}
            <p>Followers: {{ profile.followers.all.count }}</p>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock content %}

test_django/templates/show_notifications.html
<div class="dropdown">
    <span class="badge bg-primary notification-badge" onclick="showNotifications()">{{ notifications.count }}</span>
    <div class="dropdown-content d-none" id="notification-container">
        {% for notification in notifications %}
        {% if notification.photo %}
        {% if notification.notification_type == 1 %}
        <div class="dropdown-item-parent">
            <a href="{% url 'post-notification' notification.pk notification.photo.pk %}">@{{ notification.from_user }}
                liked your post</a>
            <span class="dropdown-item-close"
                  onclick="removeNotification(`{% url 'notification-delete' notification.pk %}`, `{{ request.path }}`)">&times;</span>
        </div>
        {% elif notification.notification_type == 2 %}
        <div class="dropdown-item-parent">
            <a href="{% url 'post-notification' notification.pk notification.photo.pk %}">@{{ notification.from_user }}
                commented on your post</a>
            <span class="dropdown-item-close"
                  onclick="removeNotification(`{% url 'notification-delete' notification.pk %}`, `{{ request.path }}`)">&times;</span>
        </div>
        {% endif %}
        {% elif notification.comment %}
        {% if notification.notification_type == 1 %}
        <div class="dropdown-item-parent">
            <a href="{% url 'post-notification' notification.pk notification.comment.photo.pk %}">@{{
                notification.from_user }} liked your comment</a>
            <span class="dropdown-item-close"
                  onclick="removeNotification(`{% url 'notification-delete' notification.pk %}`, `{{ request.path }}`)">&times;</span>
        </div>
        {% elif notification.notification_type == 2 %}
        <div class="dropdown-item-parent">
            <a href="{% url 'post-notification' notification.pk notification.comment.photo.pk %}">@{{
                notification.from_user }} replied to your comment</a>
            <span class="dropdown-item-close"
                  onclick="removeNotification(`{% url 'notification-delete' notification.pk %}`, `{{ request.path }}`)">&times;</span>
        </div>
        {% endif %}
        {% else %}
        <div class="dropdown-item-parent">
            <a href="{% url 'follow-notification' notification.pk notification.from_user.profile.pk %}">@{{
                notification.from_user }} has started following you</a>
            <span class="dropdown-item-close"
                  onclick="removeNotification(`{% url 'notification-delete' notification.pk %}`, `{{ request.path }}`)">&times;</span>
        </div>
        {% endif %}
        {% endfor %}
    </div>
</div>

test_django/templates/update_photo.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %} Gallery-update/pic {% endblock %}
{% block content %}

<div class="row">
    <div class="col-md-6">
        <div class="card card-body">

            <form action="" method="POST">
                {% csrf_token %}
                {{form|crispy}}

                <input type="submit" name="Submit">
            </form>

        </div>
    </div>
</div>

{% endblock %}